version: "3"
services:
  redis:
    image: redis
    container_name: redis
    volumes:
      - ./redis:/data
    ports:
      - 6379:6379
  apm:
    build:
      context: ./apm
      dockerfile: Dockerfile
    container_name: apm
    ports:
      - 8200:8200
    depends_on:
      - es
  es:
    image: elasticsearch:8.2.2
    container_name: elasticsearch
    ports:
    - 9200:9200
    - 9300:9300
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=Test123
    volumes:
      - ./elasticsearch/:/usr/share/elasticsearch/data
  kibana: 
    container_name: kibana
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    image: kibana:8.2.2
    ports:
    - 5601:5601

  fe:
   image: telkomindonesia/alpine:nginx-1.12.2-novol
   ports:
    - 8081:8080
   env_file:
    - ./client/.env
   container_name: frontend
   volumes:
    -  ./client/dist/:/var/www/data/html
   depends_on:
    - be
  be:
   build:
    context: ./server
    dockerfile: Dockerfile
   ports:
     - 5050:5051
   env_file:
    - ./server/.env
   container_name: backend
   depends_on:
    - db
    - redis
    - apm
  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongodb
    volumes:
      - ./database:/db
      - ./mongodb:/data/db