version: "3"
services:
  minio:
    image: telkomindonesia/debian:minio-1.0
    ports:
      - 9000:9000
    volumes:
      - ./minio:/data/minio
    container_name: minio
    environment:
      - MINIO_ACCESS_KEY=Test1234567
      - MINIO_SECRET_KEY=Test1234567
      - MINIO_BROWSER=on
  redis:
    image: redis
    container_name: redis
    volumes:
      - ./redis:/data
    ports:
      - 6379:6379
  apm:
    build:
      context: ./apm
      dockerfile: Dockerfile
    container_name: apm
    ports:
      - 8200:8200
    depends_on:
      - es
  es:
    image: elasticsearch:8.2.2
    container_name: elasticsearch
    ports:
    - 9200:9200
    - 9300:9300
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=Test123
    volumes:
      - ./elasticsearch/:/usr/share/elasticsearch/data
  kibana: 
    container_name: kibana
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    image: kibana:8.2.2
    ports:
    - 5601:5601

  fe:
   image: nginx
   ports:
    - 8081:80
   env_file:
    - ./client/.env
   container_name: frontend
   volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    -  ./client/dist/:/usr/share/nginx/html
   depends_on:
    - be
  be:
   build:
    context: ./server
    dockerfile: Dockerfile
   ports:
     - 5050:5051
   env_file:
    - ./server/.env
   container_name: backend
   depends_on:
    - db
    - redis
    - apm
  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongodb
    volumes:
      - ./database:/db
      - ./mongodb:/data/db