version: "3"
services:
  fe:
   image: telkomindonesia/alpine:nginx-1.12.2-novol
   ports:
    - 8081:8080
   env_file:
    - ./client/.env
   container_name: frontend
   volumes:
    -  ./client/dist/:/var/www/data/html
   depends_on:
    - be
  be:
   #image: telkomindonesia/alpine:nodejs-14
   build:
    context: ./server
    dockerfile: Dockerfile
   #command:
    #- ls
    # - node -v
    #- npm run start
   ports:
     - 5050:5051
   env_file:
    - ./server/.env
   container_name: backend
   #volumes:
   # - ./server:/usr/app/src
   depends_on:
    - db
  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongodb
    volumes:
      - ./database:/db
      - ./mongodb:/data/db

# networks:
  # mern-stack-net:
    # driver: bridge

# volumes:
  # mongo-data:
    # driver: local